### PR TITLE
Sampling Potentials Architecture

### PR DESCRIPTION
**Pull request by nstarman**
## Description

Before we start calculating residuals, we want a code-agnostic method of sampling from a potential.
This introduces a registry system for adding sampling classes.

## PR Checklist

- [x] Check out the [contributing guidelines](https://github.com/astropy/astropy/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/astropy/astropy/blob/master/CODE_OF_CONDUCT.md)
- [x] Check out the [contributing workflow](http://docs.astropy.org/en/latest/development/workflow/development_workflow.html) ( for a practical example [click here](https://docs.astropy.org/en/latest/development/workflow/git_edit_workflow_examples.html#astropy-fix-example) )
- [x] Give a detailed description of the PR above.
- [x] Document changes in the `CHANGES.rst` file. See existing changelog for examples.
- [x] Add tests, if applicable, to ensure code coverage never decreases.
- [ ] Make sure the docs are up to date, if applicable, particularly the docstrings and RST files in `docs` folder.
- [x] Ensure linear history by rebasing, when requested by the maintainer.

### CODE REVIEW

**Comment by nstarman** [comment]
@CCAstro35 
I uses https://pre-commit.com to style the code. The installation and running instructions are in the link. The code styling is actually embedded in the code in the `.pre-commit-config.yaml` file, so running

```bash
cd path/to/discO
pre-commit run —all-files
```

will clean up any code and documentation

**Comment by nstarman** [comment]
Problem in installing Agama (https://github.com/GalacticDynamics-Oxford/Agama/issues/8)

**Comment by nstarman** [comment]
@CCAstro35 , except for AGAMA stuff, the test suite works well.

**Comment by nstarman** [comment]
The one thing I haven't resolved is whether ``Sampler.resample`` should return a ``SkyCoord`` with shape ``(niter, nsamp)`` or ``(nsamp, niter)``. The former makes iterating over realizations easy, the latter makes a bit more sense in terms of ordering of dimensions. I think I favor the latter, as the iteration can be achieved by taking the transpose — ``for sample in samples.T`` produces ``SkyCoord``s with shape ``(nsamp,)``.

**Comment by CCAstro35** [comment]
@nstarman I agree. (nsamp, niter) makes more intuitive sense to me dimensionally, but what you said about making realizations easier is an important point though. I can see either way, but the latter works with me.

**Comment by nstarman** [comment]
I got the measurement sampler working on shaped SkyCoord arrays. It all pipes beautifully.

**Pull request merged**
